student_name = input("Enter your name: ")
student_age = input("Enter your age: ")
roll_number = input("Enter your roll number: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
favorite_subject = input("Enter your favourite subject: ")
career_goal = input("Enter your dream career: ")

print("\n========== STUDENT INFORMATION ==========")
print("Name              :", student_name)
print("Age               :", student_age)
print("Roll Number       :", roll_number)
print("University        :", university)
print("Department        :", department)
print("Favourite Subject :", favorite_subject)
print("Career Goal       :", career_goal)
print("=========================================")
print("Thank you for using the Student Information System!")